name:  Informar un error
description: Crea un informe de error para ayudar a mejorar Marlin Firmware
title: "[BUG] (resumen del error)"
labels: ["Bug: Potential ?"]
body:
  - type: markdown
    attributes:
      value: >
        驴Quieres hacer una pregunta? 驴Buscas soporte? Por favor, utiliza uno de los [enlaces de soporte](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

  - type: markdown
    attributes:
      value: |
        **隆Gracias por informar un error en Marlin Firmware!**

        ## Antes de informar un error

        - Lee y comprende el [C贸digo de Conducta](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/code_of_conduct.md) de Marlin. Se espera que lo cumplas, incluyendo tratar a todos con respeto.

        - Prueba con la rama [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) para ver si el problema todav铆a existe.

        ## Instrucciones

        Por favor, sigue las instrucciones a continuaci贸n. Si no lo haces, es posible que tu problema sea cerrado. Consulta [Contribuir a Marlin](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md) para obtener pautas adicionales.

        1. Proporciona un buen t铆tulo que comience con [BUG].
        2. Completa todas las secciones de este formulario de informe de error.
        3. Siempre adjunta archivos de configuraci贸n para que podamos compilar y probar tu configuraci贸n.

  - type: dropdown
    attributes:
      label: 驴Probaste el c贸digo m谩s reciente de `bugfix-2.1.x`?
      description: >-
        Siempre prueba el c贸digo m谩s reciente para asegurarte de que el problema que est谩s informando a煤n no est茅 solucionado. Para descargar
        el c贸digo m谩s reciente, simplemente [haz clic en este enlace](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip).
      options:
        - S铆, y el problema todav铆a existe.
        - No, pero lo probar茅 ahora.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Detalles del Error

  - type: textarea
    attributes:
      label: Descripci贸n del Error
      description: >-
        Describe el error en esta secci贸n. Cu茅ntanos qu茅 estabas intentando hacer y qu茅
        sucedi贸 que no esperabas. Proporciona una descripci贸n clara y concisa del
        problema e incluye tantos detalles como sea posible.

        Al pegar texto formateado, no olvides poner ` ``` ` (en una l铆nea aparte) antes y despu茅s para que sea legible.
      placeholder: |
        Marlin no funciona.
    validations:
      required: true

  - type: input
    attributes:
      label: L铆nea de tiempo del Error
      description: 驴Es un error nuevo o un problema antiguo? 驴Cu谩ndo comenz贸 por primera vez?

  - type: textarea
    attributes:
      label: Comportamiento Esperado
      description: >-
        驴Qu茅 esperabas que sucediera?
      placeholder: Esperaba que se moviera hacia la izquierda.

  - type: textarea
    attributes:
      label: Comportamiento Actual
      description: 驴Qu茅 sucedi贸 realmente en su lugar?
      placeholder: Se movi贸 hacia la derecha en lugar de la izquierda.

  - type: textarea
    attributes:
      label: Pasos para Reproducir
      description: >-
        Por favor, describe los pasos necesarios para reproducir el problema.
      placeholder: |
        1. [Primer Paso] ...
        2. [Segundo Paso] ...
        3. [y as铆 sucesivamente] ...

  - type: markdown
    attributes:
      value: |
        # Tu Configuraci贸n

  - type: input
    attributes:
      label: Versi贸n de Marlin Firmware
      description: "Consulta el Men煤 Acerca de la LCD o la salida de `M115`. NOTA: Para versiones antiguas, solo corregimos errores cr铆ticos."
    validations:
      required: true

  - type: input
    attributes:
      label: Modelo de Impresora
      description: 驴Creality Ender-3, Prusa mini o Kossel Delta?

  - type: input
    attributes:
      label: Electr贸nica
      description: 驴Electr贸nica original, placa de actualizaci贸n u otra?

    - type: input
    attributes:
      label: LCD/Controller
      description: Algunos comportamientos de Marlin est谩n determinados por el controlador. Describe el modelo y la versi贸n de tu pantalla/controlador LCD.

  - type: input
    attributes:
      label: Complementos
      description: Por favor, enumera cualquier complemento de hardware que pueda estar involucrado.

  - type: dropdown
    attributes:
      label: Nivelaci贸n de la Cama
      description: 驴Qu茅 tipo de compensaci贸n de nivelaci贸n de cama est谩s usando?
      options:
        - UBL Bilinear mesh
        - ABL Bilinear mesh
        - ABL Linear grid
        - ABL 3-point
        - MBL Nivelaci贸n manual de la cama
        - Sin nivelaci贸n de cama
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Tu Slicer
      description: 驴Usas Slic3r, Prusa Slicer, Simplify3D, IdeaMaker...?
      options:
        - Slic3r
        - Simplify3D
        - Prusa Slicer
        - IdeaMaker
        - Cura
        - Otro (explicar a continuaci贸n)

  - type: dropdown
    attributes:
      label: Software de Hospedaje
      description: 驴Usas OctoPrint, Repetier Host, Pronterface...?
      options:
        - Tarjeta SD (sin conexi贸n)
        - Repetier Host
        - OctoPrint
        - Pronterface
        - Cura
        - Igual que mi slicer
        - Otro (explicar a continuaci贸n)

  - type: markdown
    attributes:
      value: |
        # Adjuntos

  - type: checkboxes
    attributes:
      label: No olvides incluir
      options:
        - label: Un archivo ZIP que contenga tu `Configuration.h` y `Configuration_adv.h`.
          required: true

  - type: markdown
    attributes:
      value: |
        ### Elementos opcionales para incluir:
        - 'Registro de salida del host. (`M111 S247` para obtener el m谩ximo registro).'
        - Im谩genes o videos que demuestren el problema, si ayuda a entenderlo.
        - Un archivo de G-Code que exponga el problema, si no afecta a _todo_ el G-Code.

  - type: textarea
    attributes:
      label: Informaci贸n adicional y archivos adjuntos
      description: >-
        Si has realizado otras modificaciones en el firmware, descr铆belas en detalle.

        Al pegar texto formateado, no olvides poner ` ``` ` (en una l铆nea aparte) antes y despu茅s para que sea legible.
