blank_issues_enabled: false
contact_links:
  - name: 📖 Marlin Documentation
    url: https://marlinfw.org/
    about: Mucha documentación sobre la instalación y el uso de Marlin.
  - name: 👤 Grupo de Facebook de MarlinFirmware
    url: https://www.facebook.com/groups/1049718498464482
    about: Por favor, haz y responde preguntas aquí.
  - name: 🕹 Marlin en Discord
    url: https://discord.gg/n5NJ59y
    about: Únete al servidor de Discord para obtener soporte y participar en discusiones.
  - name: 🔗 Foro de Discusión de Marlin
    url: https://reprap.org/forum/list.php?415
    about: Un foro web buscable alojado por RepRap dot org.
  - name: 📺 Videos de Marlin en YouTube
    url: https://www.youtube.com/results?search_query=marlin+firmware
    about: Tutoriales y más de usuarios de Marlin de todo el mundo. ¡Ideal para nuevos usuarios!
  - name: 💸 ¿Quieres donar?
    url: https://www.thinkyhead.com/donate-to-marlin
    about: ¡Echa un vistazo a las diversas opciones para apoyar el desarrollo de Marlin Firmware financieramente!

