name: ✨ Solicitar una nueva característica
description: Solicita una nueva característica para Marlin Firmware
title: "[FR] (resumen de la característica)"
labels: 'T: Solicitud de Característica'
body:
  - type: markdown
    attributes:
      value: >
        ¿Quieres hacer una pregunta? ¿Estás buscando soporte? Por favor, utiliza uno de los [enlaces de soporte](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

  - type: markdown
    attributes:
      value: >
        **¡Gracias por solicitar una nueva característica en Marlin Firmware!**

        ## Antes de solicitar una característica

        - Lee y comprende el [Código de Conducta](https://github.com/MarlinFirmware/Marlin/blob/master/.github/code_of_conduct.md) de Marlin. Se espera que cumplas con él, incluyendo el trato respetuoso hacia los demás.

        - Verifica la última rama [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) para ver si la característica ya existe.

        - Antes de proceder con tu solicitud, considera si es necesario convertirla en una característica del firmware, o si sería más adecuada como una característica del slicer o del host.

  - type: textarea
    attributes:
      label: ¿Tu solicitud de característica está relacionada con un problema? Por favor, descríbelo.
      description: Una descripción clara del problema (por ejemplo, "Necesito X pero Marlin no puede hacerlo [...]").

  - type: textarea
    attributes:
      label: ¿Estás buscando soporte para hardware?
      description: Indícanos la impresora, placa o periférico que necesita soporte.

  - type: textarea
    attributes:
      label: Describe la característica que deseas
      description: Una descripción clara de la característica y cómo crees que debería funcionar.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Contexto adicional
      description: Agrega cualquier otro contexto o capturas de pantalla sobre la solicitud de característica aquí.
