#
# check-pr.yml
# Cierra las solicitudes de extracción dirigidas a ramas de lanzamiento
#

name: PR Bad Target

on:
  pull_request_target:
    types: [opened]
    branches:
    - 1.0.x
    - 1.1.x
    - 2.0.x
    - 2.1.x

jobs:
  bad_target:
    name: PR Bad Target
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-latest

    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: >
          ¡Gracias por tu contribución! Desafortunadamente, no podemos aceptar solicitudes de extracción dirigidas a ramas de lanzamiento. Realizamos parches en las ramas de corrección de errores y solo después los lanzamos como versiones.

          Por favor, vuelve a hacer esta solicitud de extracción comenzando con la rama `bugfix-2.1.x` y asegúrate de apuntar a `bugfix-2.1.x` al volver a enviar la solicitud. Los parches también pueden apuntar a `bugfix-2.0.x` si son específicos para 2.0.9.x.

          Puede ser útil establecer la rama predeterminada de tu bifurcación en `bugfix-2.1.x`.

          Consulta [esta página](https://marlinfw.org/docs/development/getting_started_pull_requests.html) para obtener instrucciones completas.
