#
# lock-closed.yml
# Bloquea los problemas cerrados después de un período de inactividad
#

name: Bloquear Problemas Cerrados

on:
  schedule:
    - cron: '0 1/13 * * *'

jobs:
  lock:
    name: Bloquear Problemas Cerrados
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-latest

    steps:
    - uses: dessant/lock-threads@v2
      with:
        github-token: ${{ github.token }}
        process-only: 'issues'
        issue-lock-inactive-days: '60'
        issue-exclude-created-before: ''
        issue-exclude-labels: 'no-locking'
        issue-lock-labels: ''
        issue-lock-comment: >
          // Este problema ha sido bloqueado automáticamente ya que no ha habido ninguna actividad reciente después de su cierre.
          // Por favor, abre un nuevo problema para reportar errores relacionados.
        issue-lock-reason: ''
