#
# test-builds.yml
# Realiza compilaciones de prueba para detectar errores de compilación
#

name: CI

on:
  pull_request:
    branches:
    - bugfix-2.1.x
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'
  push:
    branches:
    - bugfix-2.1.x
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'

jobs:
  test_builds:
    name: Ejecutar Todas las Pruebas
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-platform:

        # Nativo
        - linux_native

        # AVR
        - mega2560
        - mega1280
        - at90usb1286_dfu

        # AVR Extendido
        - FYSETC_F6
        - melzi_optiboot
        - rambo
        - sanguino1284p
        - sanguino644p

        # SAM3X8E
        - DUE
        - DUE_archim

        # SAMD21
        - SAMD51_grandcentral_m4
        - SAMD21_minitronics20

        # ESP32
        - esp32
        - mks_tinybee

        # Teensy 2
        #- at90usb1286_cdc

        # Teensy MK20DX256
        - teensy31

        # Teensy MK64FX512, MK66FX1M0
        - teensy35

        # Teensy IMXRT1062DVx6A
        - teensy41

        # STM32F0
        - malyan_M300
        - STM32F070CB_malyan
        - STM32F070RB_malyan

        # STM32F1
        - chitu_f103
        - mks_robin
        - mks_robin_nano_v1v2
        - PANDA_PI_V29
        - STM32F103RC_btt
        - STM32F103RC_fysetc
        - STM32F103RE_btt
        - STM32F103RE_btt_USB
        - STM32F103RE_creality
        - STM32F103VE_longer
        #- mks_robin_mini
        #- mks_robin_nano_v1_3_f4_usbmod
        #- mks_robin_nano_v1v2_usbmod
        #- STM32F103CB_malyan
        #- STM32F103RC_btt_USB
        #- STM32F103RE

        # STM32F4
        - ARMED
        - BIGTREE_BTT002
        - BIGTREE_GTR_V1_0
        - BIGTREE_SKR_PRO
        - FLYF407ZG
        - FYSETC_S6
        - LERDGEK
        - LERDGEX
        - mks_robin_pro2
        - Opulo_Lumen_REV3
        - rumba32
        - STM32F401RC_creality
        - STM32F407VE_black
        - I3DBEEZ9_V1

        # STM32F7
        - NUCLEO_F767ZI
        - REMRAM_V1

        # STM32H7
        - BTT_SKR_SE_BX

        # STM32F1 (Maple)
        - jgaurora_a5s_a1_maple
        - mks_robin_lite_maple
        - mks_robin_pro_maple
        - STM32F103RC_btt_USB_maple
        - STM32F103RC_fysetc_maple
        - STM32F103RC_meeb_maple
        - STM32F103VE_longer_maple
        - STM32F103VE_ZM3E4V2_USB_maple
        #- mks_robin_maple
        #- mks_robin_nano_v1v2_maple
        #- STM32F103RC_btt_maple
        #- STM32F103RE_creality_maple

        # LPC176x - Pruebas largas
        - LPC1768
        - LPC1769

    steps:

    - name: Revisar la PR
      uses: actions/checkout@v3

    - name: Caché de pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Caché de PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Seleccionar Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7' # Rango de versiones o versión exacta de Python a utilizar, usando la sintaxis de rangos de versiones semver.
        architecture: 'x64' # opcional x64 o x86. Por defecto, x64 si no se especifica

    - name: Instalar PlatformIO
      run: |
        pip install -U platformio
        pio upgrade --dev
        pio pkg update --global

    - name: Ejecutar Pruebas de ${{ matrix.test-platform }}
      run: |
        make tests-single-ci TEST_TARGET=${{ matrix.test-platform }}
