#
# unlock-reopened.yml
# Desbloquea un problema cada vez que se reabre
#

name: "Desbloquear problema reabierto"

on:
  issues:
    types: [reopened]

jobs:
  unlock:
    name: Desbloquear Reabierto
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-latest

    steps:
    - uses: OSDKDev/unlock-issues@v1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
